%% CLEAN FUSION EPOCH FILES
clear; clc;

epoch_dir = ...
    'D:\major_project_group50\project\FUSION\data\epochs';

subjects = { ...
    'VP001','VP002','VP003','VP004','VP005','VP006', ...
    'VP007','VP008','VP009','VP010','VP011', ...
    'VP014','VP015','VP016','VP017','VP018','VP019', ...
    'VP020','VP021','VP022','VP023','VP024','VP025','VP026'};

fprintf('\n============================================\n');
fprintf(' CLEANING FUSION EPOCH FILES\n');
fprintf('============================================\n');

for s = 1:length(subjects)

    subject = subjects{s};

    filename = fullfile( ...
        epoch_dir, ...
        [subject '_nback_epochs.mat']);

    fprintf('\nProcessing %s...\n', subject);

    % Load only required variables
    data = load(filename, ...
        'eeg_epochs', ...
        'fnirs_epochs', ...
        'labels', ...
        'subject_ids', ...
        'trial_id', ...
        'eeg_start_times', ...
        'nirs_start_times', ...
        'EEG_FS', ...
        'NIRS_FS', ...
        'WINDOW_SEC');

    % Save clean file
    save(filename, ...
        '-struct', 'data', ...
        '-v7.3');

    fprintf('  Cleaned: %s\n', filename);

end

fprintf('\n============================================\n');
fprintf(' CLEANING COMPLETE\n');
fprintf('============================================\n');